cabal-version: 3.0
name: dashi
version: 0.1.0.0
synopsis: Tasty Haskell design system
homepage: https://github.com/ners/dashi/blob/master/README.md
license: Apache-2.0
license-file: LICENCE.md
author: ners
maintainer: ners@gmx.ch
bug-reports: https://github.com/ners/dashi/issues
category: System
build-type: Simple
extra-source-files:
  CHANGELOG.md
  README.md

source-repository head
  type: git
  location: https://github.com/ners/dashi

common common
  default-language: GHC2021
  ghc-options:
    -Weverything
    -Wno-unsafe
    -Wno-missing-safe-haskell-mode
    -Wno-missing-export-lists
    -Wno-missing-import-lists
    -Wno-missing-kind-signatures
    -Wno-all-missed-specialisations

  default-extensions:
    ApplicativeDo
    BlockArguments
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveGeneric
    DerivingStrategies
    DerivingVia
    ExplicitNamespaces
    LambdaCase
    NoImplicitPrelude
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings
    RecordWildCards
    RecursiveDo
    StrictData
    TypeFamilies
    ViewPatterns

  build-depends:
    base,
    containers,
    lens,
    miso,
    text,
    web-font-mdi,

library
  import: common
  hs-source-dirs: lib
  exposed-modules:
    Dashi
    Dashi.Components.ActionBar
    Dashi.Components.Avatar
    Dashi.Components.Button
    Dashi.Components.Chart
    Dashi.Components.Checkbox
    Dashi.Components.Form
    Dashi.Components.Heading
    Dashi.Components.Icon
    Dashi.Components.Link
    Dashi.Components.Message
    Dashi.Components.Plot
    Dashi.Components.ProgressBar
    Dashi.Components.Radio
    Dashi.Components.Range
    Dashi.Components.Select
    Dashi.Components.Spinner
    Dashi.Components.Switch
    Dashi.Components.Tabs
    Dashi.Components.TextField
    Dashi.Components.Util
    Dashi.Components.Widget
    Dashi.Layout.Page
    Dashi.Style
    Dashi.Style.Colour
    Dashi.Style.Root
    Dashi.Style.Tokens
    Dashi.Style.Util
    Dashi.Util
  build-depends:
    Chart,
    Chart-diagrams,
    Color,
    JuicyPixels,
    aeson,
    base64,
    clay,
    colour,
    diagrams-lib,
    identicon,
    identicon-style-squares,
    miso-diagrams,
    plots,
    pureMD5,

executable dashi
  import: common

  if arch(wasm32)
    ghc-options:
      -no-hs-main
      -optl-mexec-model=reactor
      "-optl-Wl,--export=hs_start"
    cpp-options:
      -DWASM
  if arch(javascript)
     ld-options:
       -sEXPORTED_RUNTIME_METHODS=HEAP8

  hs-source-dirs: app
  main-is: Main.hs
  other-modules:
    DSL
    Language
    Section
    Section.Avatar
    Section.Button
    Section.Checkbox
    Section.Form
    Section.Icon
    Section.Link
    Section.Message
    Section.Overview
    Section.Plot
    Section.ProgressBar
    Section.Radio
    Section.Range
    Section.Select
    Section.Spinner
    Section.Switch
    Section.Tabs
    Section.TextField
  build-depends:
    dashi,
    generic-lens,
    extra,
    fluent-bundle,
    fluent-syntax,
